### ISSUE TITLE
TDL 7.0 RC2 - Correct icon for multiple file links?

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [abstractspoon/ToDoList_Resources#8]
What is the right icon for file-links if there are more than one link? Maybe a neutral icon should be displayed, without click-functionality?

**Comment by abstractspoon** [comment]
It's always the first one, which can be changed by selecting in the 'File Links' attribute field.

My feeling was that this supports the idea of a 'Primary' file links with zero or more 'secondary' links, so that the primary is most accessible but the others are accessible with a little more effort.

Alternatively (7.1) I could widen the File Link column and displays all the file link icon for a task.

**Comment by Pierre-de-la-Verre** [comment]
> Alternatively (7.1) I could widen the File Link column and displays all the file link icon for a task.

 

 

Yes, I think this would be fine.

 

Pierre

 

 

Von: abstractspoon [mailto:notifications@github.com] 
Gesendet: Montag, 13. Juli 2015 09:50
An: abstractspoon/ToDoList_Resources
Cc: Pierre-de-la-Verre
Betreff: Re: [ToDoList_Resources] TDL 7.0 RC2 - Correct icon for multiple file links? (#8)

 

It's always the first one, which can be changed by selecting in the 'File Links' attribute field.

My feeling was that this supports the idea of a 'Primary' file links with zero or more 'secondary' links, so that the primary is most accessible but the others are accessible with a little more effort.

Alternatively (7.1) I could widen the File Link column and displays all the file link icon for a task.

**Comment by abstractspoon** [comment]
This issue was moved to abstractspoon/ToDoList_Wiki#5
